# Generated by Django 3.0.6 on 2020-05-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.CharField(default='white', max_length=5),
        ),
    ]
