# Generated by Django 3.0.6 on 2020-05-29 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_projects_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='color',
        ),
    ]
