# Generated by Django 3.0.6 on 2020-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_projects_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='color',
            field=models.CharField(max_length=6),
        ),
    ]
