# Generated by Django 3.0.6 on 2020-06-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200528_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
