# Generated by Django 3.0.6 on 2020-06-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_projects_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
