# Generated by Django 3.0.6 on 2020-06-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200609_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
