# Generated by Django 3.0.6 on 2020-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_projects_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
