# Generated by Django 3.0.6 on 2020-06-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200610_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
