# Generated by Django 3.0.6 on 2020-06-12 19:11

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200611_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.get_image_filename, verbose_name='Image')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Projects')),
            ],
        ),
    ]
